### PR TITLE
Pass current loopback user id into credentials functions

### PR DESCRIPTION
**Pull request by alexkolson**
This would greatly aid me in a current use case I have where Im storing the
actual credentials in redis and I look them up by user id. Or rather, I would
like to be able to look them up by user id but in order to do that I need to have
access to the current user id in the credentials functions.

### CODE REVIEW

**Comment by alexkolson** [comment]
Any thoughts @benkroeger?

**Review by benkroeger — COMMENTED** [review]
these look like breaking changes. did you inspect the `credentials` object? if it is the credentials instance from loopback model (loopback-component-passport) then it should have a `userId` property (created from the credentials belongsTo User relation

**Comment by benkroeger** [comment]
also, is this maybe something that should better be done somewhere on the auth-provider level? If we're going for a breaking change, we might as well do it right?!

**Comment by alexkolson** [comment]
Agreed about that an auth provider is maybe the better place for this.

As far as the credentials object goes, I thought I tried to grab userId and it wasn't there but I will try again. 😄

**Comment by alexkolson** [comment]
@benkroeger 

Ok so further inspection reveals that you can pretty much put whatever you want in the credentials and it is up to each individual auth scheme what exactly is in there.

So now I am thinking that maybe we don't need to introduce such a breaking change here in this package and instead i can use `makeVerifyFunction()` to plant a dummy credentials object that just has userId in it.

**Comment by alexkolson** [comment]
Hmm...this has to take place in a request context in order to have userId and I keep forgetting that.

**Pull request closed without merging**
